POST https://sulpro-weather-station.herokuapp.com/api/newreading
Content-Type: application/json

{
  "name":"YokkilaSensor",
  "temperature":24.42,
  "pressure":100511.3,
  "humidity":21.69,
  "longitude": "22.288723",
  "latitude": "60.461212"
}
