POST http://sulpro-weather-station.herokuapp.com/api/newreading
Content-Type: application/json

{
  "name": "TestSensor",
  "temperature": 25.38,
  "pressure": 101227.7,
  "humidity": 20.27832,
  "longitude": "22.288723",
  "latitude": "60.461212"
}
